### ISSUE TITLE
Timezone doesn't show on user profile anymore after recent discord update

### ISSUE THREAD

**Issue by idntknwlouis** [Syncxv/vc-timezones#2]
yep...
![image_2024-05-15_100759601](https://github.com/Syncxv/vc-timezones/assets/107615094/a8ae94d9-689b-49f1-a3ac-3699f13770fa)

It still works, but it doesn't appear on user profile
![image_2024-05-15_101146926](https://github.com/Syncxv/vc-timezones/assets/107615094/3090ab25-bc40-41de-a6a4-b190cb3ab658)
![image_2024-05-15_101112842](https://github.com/Syncxv/vc-timezones/assets/107615094/33e3585d-7e8e-44d9-a060-fcf73a0e33ab)

**Comment by Syncxv** [comment]
discord seems to have fixed thier sidebar banner overflowing. so it seems to works now
![image](https://github.com/Syncxv/vc-timezones/assets/47534062/7d88a691-6f87-48cd-b6f8-fd99238eb883)

**Comment by pinetreemoonlight** [comment]
> discord seems to have fixed thier sidebar banner overflowing. so it seems to works now ![image](https://private-user-images.githubusercontent.com/47534062/341265312-7d88a691-6f87-48cd-b6f8-fd99238eb883.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzk4NjIsIm5iZiI6MTcyNDI3OTU2MiwicGF0aCI6Ii80NzUzNDA2Mi8zNDEyNjUzMTItN2Q4OGE2OTEtNmY4Ny00OGNkLWI2ZjgtZmQ5OTIzOGViODgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDIyMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMDcwY2YzMDdlZDk2ZWI4MGJlMTU5ODEzOTM3YTVlYjk4YjQyNjBiMjkzOWIxNDdiMGIzMWQ5MTU1YmFmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-mcymk8Olc9qHRCSvvhYoJWcd7tQY7gSUIT6pA9X5XQ)

Is that the same issue we are having currently (22 August 2024)? Cause Timezones in chat do work, but in the sidebar they're gone again. Or is there a fix? I tried updating css classes of the styles file, but that also didn't work.

**Comment by idntknwlouis** [comment]
>Cause Timezones in chat do work, but in the sidebar they're gone again.

yep, they're gone again. even on profile pop-outs.
