### ISSUE TITLE
Will this plugin be fixed after the 19 June Discord update?

### ISSUE THREAD

**Issue by okielua** [Syncxv/vc-timezones#3]
Would be AMAZING. 

Currently it is not working at all: 

- timezones don't show anywhere
- the right-click menu entry to set timezones is not visible 

I would be willing to donate to anyone who fixes this plugin because it's so essential to me.

**Comment by TheMrGong** [comment]
Try the fix: https://github.com/Syncxv/vc-timezones/pull/4

**Comment by okielua** [comment]
> Try the fix: #4


I applied the fix, but nothing changed. Does it work for you?

**Comment by Syncxv** [comment]
fixed here 836eb2b
